python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 0
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 5
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 10
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 15
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 20
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 25
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 30
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 35
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 40
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 45
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 50
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 55
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 60
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 65
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 70
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 75
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 80
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 85
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 90
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 95
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 100
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 105
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 110
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 115
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 120
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 125
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 130
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 135
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 140
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 145
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 150
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 155
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 160
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 165
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 170
python make_cnet_dataset.py --audio_dir "raw-audio/" --train_data_dir "train-data/" --prompt_file "prompt_labels.json" --limit 5 --start_ind 175